# -*- coding: utf-8 -*-
"""
Windows desktop step definitions placeholder.

These steps will be auto-generated by AutoGenesis when you execute tests
using Claude Code or the CLI.
"""

from behave import given, when, then, step


@given('Notepad is launched')
def step_notepad_launched(context):
    """Launch Notepad application."""
    # from skills.desktop_windows_skill.session_manager import WindowsSessionManager
    # context.app_session = WindowsSessionManager(context.config.get('notepad', {}))
    # context.app_session.app_launch(kill_existing=1)
    raise NotImplementedError("Use AutoGenesis to generate this step")


@when('I type "{text}" in the editor')
def step_type_text(context, text):
    """Type text in the editor."""
    # context.app_session.enter_text(element_info={"control_type": "Edit"}, text=text)
    raise NotImplementedError("Use AutoGenesis to generate this step")


@when('I press {shortcut} to {action}')
def step_keyboard_shortcut(context, shortcut, action):
    """Press a keyboard shortcut."""
    # context.app_session.send_keystrokes(keys=shortcut)
    raise NotImplementedError("Use AutoGenesis to generate this step")


@when('I click the "{menu}" menu')
def step_click_menu(context, menu):
    """Click a menu item."""
    # context.app_session.element_click(element_info={"title": menu, "control_type": "MenuItem"})
    raise NotImplementedError("Use AutoGenesis to generate this step")


@then('the file should be saved successfully')
def step_verify_saved(context):
    """Verify file was saved."""
    raise NotImplementedError("Use AutoGenesis to generate this step")
